proxy:
  image: darksnake/identiproxy
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=127.0.0.1
    - NGINX_PROXY=http://identidock:9090

identidock:
  image: darksnake/identidock:1.0
  environment:
    ENV: PROD
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:3.0

logspout:
  image: amouat/logspout-logstash
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "8000:80"
  links:
    - logstash
  command: logstash://logstash:5000

logstash:
  image: logstash:7.8.0
  volumes:
    - ./logstash.conf:/etc/logstash.conf
  environment:
    LOGSPOUT: ignore
  command: -f /etc/logstash.conf
